### ISSUE TITLE
Search field in Characters oveflows

### ISSUE THREAD

**Issue by modehnal** [zach-herridge/poestack-next#3]
![overflow_no_highlight](https://user-images.githubusercontent.com/40463522/217580075-818eebee-321a-4e0b-8366-92bae0af606f.png)

![overflow](https://user-images.githubusercontent.com/40463522/217580090-44ba3a30-30a0-487f-b663-084919fa5e6b.png)

To fix this I added the max-width to the element.
```
element.style {
  max-width: calc(100% - 10px);
}
```
With following result

![fix](https://user-images.githubusercontent.com/40463522/217580744-6f6ce440-408e-4392-85da-5645ddbef9a9.png)

I am sure there is much better place to make this fix since I did not go through your code. Just opened the page and saw the overflow.

**Comment by zach-herridge** [comment]
Thanks the issue should be resolved in https://github.com/zach-herridge/poestack-next/pull/5
