### ISSUE TITLE
Menu items could use some padding

### ISSUE THREAD

**Issue by modehnal** [zach-herridge/poestack-next#4]
The padding could improve readability.
![padding](https://user-images.githubusercontent.com/40463522/217583046-3f4a6397-86f7-4bde-8224-6a4d01446522.png)

Also the slider could have a little tweaked background colour to be more easily seen. Maybe a simple padding in the slider background would suffice just to separate those two object with the same colour.

**Comment by tme321** [comment]
I submitted a pull request to fix this.

**Comment by zach-herridge** [comment]
This should be out now!
